project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    code_fold: true
    df_print: kable
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default



